import React, { FC, useState } from "react";
import Head from "next/head";
import { Nav } from "./Nav";
import { Footer } from "./Footer";
import CartSlide from "./CartSlide";

interface Props {
  title: string;
  children: React.ReactNode;
}

const Layout: FC<Props> = ({ title, children }) => {
  const [modalVisible, setModalVisible] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>{title ? title : "Hello Ecommerce"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <CartSlide
          modalVisible={modalVisible}
          setModalVisible={setModalVisible}
        />
        <div
          className={
            modalVisible
              ? "opacity-70 flex flex-col min-h-screen justify-between relative"
              : "flex flex-col min-h-screen justify-between relative "
          }>
          <header className="sticky top-0 z-50">
            <Nav setModalVisible={setModalVisible} />
          </header>
          <main className="item-center">{children}</main>
          <footer>
            <Footer />
          </footer>
        </div>
      </>
    </>
  );
};

export default Layout;
