const data = {
  products: [
    {
      name: 'Jordan Two Trey',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/treyMain.webp',
      price: 135.00,
      brand: 'Jordan',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
     {
      name: 'adidas Eastrail 2.0 Hiking Shoes',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/adidas-Eastrail.webp',
      price: 85.00,
      brand: 'adidas',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Take in a sweeping vista. Hike to a waterfall. Cruise across town. Feel the freedom to roam in the comfort of these adidas hiking shoes. Abrasion-resistant overlays on a breathable mesh upper hold up to the scuffs and scrapes of big adventures while lightweight cushioning keeps you comfortable on your feet. Even in rugged terrain, the Traxion outsole ensures confident footing.',
    },
    {
      name: 'Jordan Air 1 Mid SE',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/Jordan1.webp',
      price: 135.00,
      brand: 'Jordan',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "Need a sneaker refresh? Then cop these men's Air 1 Mid trainers from Jordan. Coming in a Black and Fire Red colourway, these kicks have an upper made from a blend of genuine and synthetic leather for lasting durability. They feature a lace fastening with a mid-cut padded ankle collar to keep your feet snug and secure. Underfoot is a soft foam midsole that uses Nike Air tech for next level cushioned comfort and rubber outsole max' grip. With perforations to the toe for breathability, they're signed off with the Wings logo to the heel and a Swoosh to the sidewalls.",
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
     {
      name: 'adidas Ultraboost 1.0 Shoes',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/adidas-Ultraboost.webp',
      price: 160.00,
      brand: 'adidas',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: "These adidas Ultraboost running shoes combine the most advanced adidas technology for a performance that has to be felt to be believed. The sock-like adidas Primeknit upper has been redesigned to allow air to flow freely. A supportive heel counter supports the back of your foot, while adidas BOOST delivers maximum comfort and energy return. The Stretchweb outsole is made with Continental™ Rubber for a firm grip and a smooth ride.This shoe's upper is made with a high-performance yarn which contains at least 50% Parley Ocean Plastic — reimagined plastic waste, intercepted on remote islands, beaches, coastal communities and shorelines, preventing it from polluting our ocean. The other 50% of the yarn is recycled polyester.",
    },
    {
      name: 'Jordan Point Lane',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/Jordan-Point.webp',
      price: 90,
      brand: 'Jordan',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Nike Air Force 1 07 LV8',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/NikeAirForce.webp',
      price: 115.00,
      brand: 'Nike',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: "Exclusive to JD. Elevate your rotation with these men's Air Force 1 '07 LV8 sneakers from Nike. In a Cargo Khaki colourway, these refreshed classics have a premium leather and synthetic upper for a soft yet durable wear. They feature a low-cut, padded ankle collar for a comfy fit, as well as a tonal lace-up front and heel pull for easy access. Underfoot, the contrasting foam midsole houses Nike Air cushioning for a responsive step, while the rubber outsole has hoops pivot circles for an OG look and standout grip. Signed off with the iconic Swoosh logo to the sidewalls and Nike Air branding at the heel and tongue",
    },
  ],
};

export default data;