import Head from "next/head";
import React, { FC } from "react";
import Sidebar from "./Sidebar";
import TopBar from "./TopBar";

interface Props {
  title: string;
  children: React.ReactNode;
}

const AdminLayout: FC<Props> = ({ title, children }) => {
  return (
    <>
      <Head>
        <title className="capitalize">
          {title ? `${title} - Hello Ecommerce` : "Hello Ecommerce"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-between relative">
        <header className="fixed h-screen w-[18%]">
          <Sidebar />
        </header>
        <div className="w-[82%] relative left-[18%]">
          <TopBar />
          <main>{children}</main>
        </div>
      </div>
    </>
  );
};

export default AdminLayout;
