import Head from "next/head";
import React, { FC } from "react";
import Sidebar from "./Sidebar";
import TopBar from "./TopBar";

interface Props {
  title: string;
  children: React.ReactNode;
}

const AdminLayout: FC<Props> = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title ? title : "Hello Ecommerce"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 md:grid-cols-12">
        <header className="col-span-2 sticky">
          <Sidebar />
        </header>
        <div className="col-span-10">
          <TopBar />
          <main>{children}</main>
        </div>
      </div>
    </>
  );
};

export default AdminLayout;
